version: '3'

networks:
  http_network:
    external: true

services:
  backend:
    build: backend
    restart: always
    networks:
      - http_network
    labels:
      - "traefik.enable=true"
      - "trae