version: '3'

networks:
  http_network:
    external: true

services:
  backend:
    build: backend
    restart: always
    networks:
      - http_network
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:staging.webml.app;PathPrefixStrip:/backend/"
      - "traefik.port=10201"
 